### ISSUE TITLE
Exchange at different location

### ISSUE THREAD

**Issue by micha-sommer** [ThomDietrich/multiUAV-simulation#31]
Should this be even possible?:
![image](https://user-images.githubusercontent.com/638368/37091880-0533d6bc-220a-11e8-9343-4a481a145776.png)
Can be reconstructed with b60ea107bea2a23751b4c23f30b7e16a8cb5de67 and inifile configuration *mission-Nr-01*.

**Comment by ThomDietrich** [comment]
This is imho the reason for #32.

In the log I'm seeing

```
INFO (UAVNode)OsgEarthNet.uav[0]: Energy Management: OK. UAV has enough energy to continue (12%).
```

even though the UAV should switch into EX mode. 

As expected this issue is related to your short mission of only two commands. Duplicating those commands in `mission1.waypoints` solves both issues. However, this can't be the solution. Could you please extend the prediction algorithm(s) to loop commands (if mission was defined with the repeat flag)?

**Comment by m0zi** [comment]
I'll have a look into it.
